module.exports = {
  SOCKET_CONNECT: 'SOCKET_CONNECT',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',

  DATA_CHANGED: 'DATA_CHANGED',

  GET_MEETING_LIST: 'GET_MEETING_LIST',
  CREATE_MEETING: 'CREATE_MEETING',
  CREATE_PERSON: 'CREATE_PERSON',

  GET_VOTING_STATUS: 'GET_VOTING_STATUS',
  UPDATE_VOTING_ANSWER: 'UPDATE_VOTING_ANSWER',
  UPDATE_VOTING_POINT: 'UPDATE_VOTING_POINT',

  GET_MEETING_DATA: 'GET_MEETING_DATA',
  REVEAL_REPORT:'REVEAL_REPORT',
  RESET:'RESET'
};